### ISSUE TITLE
PGP plugin is not recognized by Airmail 3

### ISSUE THREAD

**Issue by anunayk** [Airmail/AirmailPlugIn-Framework#34]
I wonder why #25 was closed. The bundle is not recognized and it's never listed in the plugins screen. I'm running 3.5.6 (481) on macOS 10.13.4.

**Comment by Lord-Kamina** [comment]
Same here... two years and still no fix?

**Comment by alexandernst** [comment]
3.6.1 (506), PGP plugin still not recognized

**Comment by xilopaint** [comment]
> 3.6.1 (506), PGP plugin still not recognized

Airmail doesn't care for your privacy. Simple as that.

**Comment by alexandernst** [comment]
I found out why it's not showing. You must install https://gpgtools.org

**Comment by gnuget** [comment]
It seems that this problem is back now at Mac Os 10.14 Mojave and Airmail 3.6.41 (524)

as @alexandernst  said the plugin used to work after installing gpgtools but now even having it installed the plugin is not recognized :-/

**Comment by alexandernst** [comment]
@gnuget you need to upgrade to the latest version of GPG Suite (yes, the one that is paid)

**Comment by gnuget** [comment]
I just paid and... it didn't work :-/ 

What I did was: 

- Pay on their web page, 
- Open the mail and follow the instructions (open the mail app, open the plugin dialog, put the activation code, and restart the mail app)
- I open again airmail
- open the plugins dialog and... empty :-(

**Comment by gnuget** [comment]
I just contacted the Airmail support and they just confirmed that the plugins are disabled for Mac Os Mojave :-/

**Comment by yannickmcosta** [comment]
Not good, the fact that the app doesn't inform you that the plugins are disabled in the most recent build and silently fails is *really* not ideal. Any idea when this will be fixed as given the current attitude of the internet where encryption and data security is concerned, it may take moving to another mail client.

**Comment by Bloophub** [comment]
A version with fix is in approval by App Store is just taking longer then usual.

**Comment by zentavr** [comment]
3.6.43 came to me today and the plugin is still not visible.

**Comment by zentavr** [comment]
When I run the app from the command line, it says:
```
2018-10-10 22:56:27.785 Airmail 3[3506:40673] [BASE] ------ ------ ------ ------ ------ ------ ------
2018-10-10 22:56:27.785 Airmail 3[3506:40673] [BASE] Airmail Type:STORE OSX:10.14.0 Version:527
2018-10-10 22:56:29.466 Airmail 3[3506:40673] Error loading /Users/zentavr/Library/Group Containers/2E337YPCZY.airmail/Library/Application Support/it.bloop.airmail2/Airmail/General/Plugins/AMPGpg.bundle/Contents/MacOS/AMPGpg:  dlopen(/Users/zentavr/Library/Group Containers/2E337YPCZY.airmail/Library/Application Support/it.bloop.airmail2/Airmail/General/Plugins/AMPGpg.bundle/Contents/MacOS/AMPGpg, 265): Library not loaded: @rpath/Libmacgpg.framework/Versions/B/Libmacgpg
  Referenced from: /Users/zentavr/Library/Group Containers/2E337YPCZY.airmail/Library/Application Support/it.bloop.airmail2/Airmail/General/Plugins/AMPGpg.bundle/Contents/MacOS/AMPGpg
  Reason: image not found
```

**Comment by Lord-Kamina** [comment]
Well now that's interesting.

**Comment by zentavr** [comment]
The GPG worked before. When I recover the app from Time Machine - it does not see any of the plugins.

**Comment by Lord-Kamina** [comment]
Yeah but that error is something to work with. It's a dependency incompatibility. It might be possible to build a new version of the framework it depends on or something like that.

**Comment by zentavr** [comment]
@Lord-Kamina: I had tried to build with XCode 10.0 (10A255) and have the same problem..

**Comment by Lord-Kamina** [comment]
> @Lord-Kamina: I had tried to build with XCode 10.0 (10A255) and have the same problem..

Let me make an analogy... I'm telling you "Your car won't start because it's missing a fuse." and you just replied "That cannot possibly be the issue, I just painted it a new color today."

**Comment by zentavr** [comment]
@Lord-Kamina ok, let me explain:
I did a checkout of this repo. It has a submodule of *Libmacgpg.framework* as a dependency (but some outdated commit). I checked that out as well. After that I tried to build with the submodule-commit, then with the latest master branch. Nothing.. Maybe there is a trick in the XCode Project configuration?

**Comment by zentavr** [comment]
@Bloophub which version did you have in mind? 3.6.50 and still no plugin is recognised...

**Comment by MTCoster** [comment]
Still an issue on the 3.7.0 beta:

```
2018-10-21 17:19:18.467 Airmail Beta[95582:1980691] [BASE] Airmail Type:PUBLIC BETA OSX:10.14.0 Version:529
2018-10-21 17:19:19.226 Airmail Beta[95582:1980691] [INFO] Loaded Plugin Read Receipt This plug-in implements a Read Receipt system.
2018-10-21 17:19:19.229 Airmail Beta[95582:1980691] Error loading /Users/Matt/Library/Group Containers/2E337YPCZY.airmail/Library/Application Support/it.bloop.airmail.beta11/Airmail/General/Plugins/AMPGpg.bundle/Contents/MacOS/AMPGpg:  dlopen(/Users/Matt/Library/Group Containers/2E337YPCZY.airmail/Library/Application Support/it.bloop.airmail.beta11/Airmail/General/Plugins/AMPGpg.bundle/Contents/MacOS/AMPGpg, 265): Library not loaded: @rpath/Libmacgpg.framework/Versions/B/Libmacgpg
  Referenced from: /Users/Matt/Library/Group Containers/2E337YPCZY.airmail/Library/Application Support/it.bloop.airmail.beta11/Airmail/General/Plugins/AMPGpg.bundle/Contents/MacOS/AMPGpg
  Reason: image not found
2018-10-21 17:19:19.229 Airmail Beta[95582:1980691] [ERR] Cannot Load Plugin {
    BuildMachineOSBuild = 16G29;
    CFBundleDevelopmentRegion = English;
    CFBundleExecutable = AMPGpg;
    CFBundleIdentifier = "it.bloop.airmail.plugin.gpg";
    CFBundleInfoDictionaryVersion = "6.0";
    CFBundleName = AMPGpg;
    CFBundleNumericVersion = 67141632;
    CFBundlePackageType = BNDL;
    CFBundleShortVersionString = "1.0";
    CFBundleSignature = "????";
    CFBundleSupportedPlatforms =     (
        MacOSX
    );
    CFBundleVersion = 4;
    DTCompiler = "com.apple.compilers.llvm.clang.1_0";
    DTPlatformBuild = 9M214v;
    DTPlatformVersion = GM;
    DTSDKBuild = 17A350a;
    DTSDKName = "macosx10.13";
    DTXcode = 0900;
    DTXcodeBuild = 9M214v;
    NSHumanReadableCopyright = "Copyright \U00a9 2014 bloop. All rights reserved.";
    NSPrincipalClass = AMPGpg;
} (null) (null)
```

**Comment by Lord-Kamina** [comment]
Where are you all placing Libmacgpg.framework?

**Comment by MTCoster** [comment]
@Lord-Kamina GPG Suite installed it to `/Library/Frameworks/Libmacgpg.framework` for me (I assume this is the default - I've done nothing to suggest otherwise).

**Comment by zentavr** [comment]
@Lord-Kamina, I have GPG Suite in `/Library/Frameworks/Libmacgpg.framework` as well.

**Comment by zentavr** [comment]
```
zentavr@zentavr-mac:/Library/Frameworks/Libmacgpg.framework
2018-10-21 21:13:56 EEST $ ls -la
total 0
drwxr-xr-x   6 root  wheel  192 21 жов 00:22 .
drwxr-xr-x  12 root  wheel  384 21 жов 00:22 ..
lrwxr-xr-x   1 267   267     24 21 жов 00:22 Headers -> Versions/Current/Headers
lrwxr-xr-x   1 267   267     26 21 жов 00:22 Libmacgpg -> Versions/Current/Libmacgpg
lrwxr-xr-x   1 267   267     26 21 жов 00:22 Resources -> Versions/Current/Resources
drwxr-xr-x   4 root  wheel  128 21 жов 00:22 Versions
zentavr@zentavr-mac:/Library/Frameworks/Libmacgpg.framework
2018-10-21 21:15:34 EEST $ ls -la ./Versions/
total 0
drwxr-xr-x  4 root  wheel  128 21 жов 00:22 .
drwxr-xr-x  6 root  wheel  192 21 жов 00:22 ..
drwxr-xr-x  6 root  wheel  192 21 вер 02:03 B
lrwxr-xr-x  1 267   267      1 21 жов 00:22 Current -> B
```

**Comment by rogerwalczak** [comment]
Rebuilding this plugin seems to help.
[AMPGpg.bundle.zip](https://github.com/Airmail/AirmailPlugIn-Framework/files/2507810/AMPGpg.bundle.zip)

**Comment by zentavr** [comment]
@rogerwalczak, I wonder what the steps were done in order to do the build? I tried to build on Mojave and caught the same error.

**Comment by Lord-Kamina** [comment]
> @rogerwalczak, I wonder what the steps were done in order to do the build? I tried to build on Mojave and caught the same error.

He changed `@rpath` for explicitly linking to the framework in /Library/:

```
AMPGpg.bundle/Contents/MacOS/AMPGpg:
	@executable_path/../Frameworks/AMPluginFramework.framework/Versions/A/AMPluginFramework (compatibility version 1.0.0, current version 1.0.0)
	/Library/Frameworks/Libmacgpg.framework/Versions/B/Libmacgpg (compatibility version 2.0.0, current version 2.0.0)
	/System/Library/Frameworks/Cocoa.framework/Versions/A/Cocoa (compatibility version 1.0.0, current version 23.0.0)
	/System/Library/Frameworks/Foundation.framework/Versions/C/Foundation (compatibility version 300.0.0, current version 1555.10.0)
	/usr/lib/libobjc.A.dylib (compatibility version 1.0.0, current version 228.0.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1252.200.5)
	/System/Library/Frameworks/AppKit.framework/Versions/C/AppKit (compatibility version 45.0.0, current version 1670.0.0)
	/System/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation (compatibility version 150.0.0, current version 1555.10.0)
```
Although probably a better solution would be to bundle Libmacgpg.framework with the plug-in and add proper rpaths to the executable.

Also, Libmacgpg apparently uses ObjC GC, which was deprecated ages ago. I tried converting it on my machine to ARC but I think my Xcode might be broken and it didn't work.

**Comment by rogerwalczak** [comment]
Mojave build:
1. Build recent version of Libmacgpg.framework
2. Open AMPGpg.xcodeproj in Xcode (don’t make ARC conversion)
3. Remove reference to Libmacgpg.xcodeproj from project
4. Copy Libmacgpg.framework and AMPluginFramework.framework to project folder.
5. Remove references to AMPluginFramework.framework and Libmacgpg.framework and add them again indicating just copied frameworks
6. Build.

Build will fail on post processing step - copying bundle file to non existent directory (at least in my case. Didn’t bother to fix it) - but you will find the file in ~/Library/Developer/…. (Long path) 
-- 
R

On 23 October 2018 at 22:19:48, Andrey Miroshnichenko (notifications@github.com) wrote:

@rogerwalczak, I wonder what the steps were done in order to do the build? I tried to build on Mojave and caught the same error.

**Comment by KodaKoder** [comment]
Just updated the code and the plugin 
let me know if is all ok 
https://rink.hockeyapp.net/apps/12d0753a9a3cecd2f00b262409be4ec2

**Comment by zentavr** [comment]
@KodaKoder - The error still exists:
```
/Applications/Airmail\ 3.app/Contents/MacOS/Airmail\ 3
objc[95032]: Class SSKeychain is implemented in both /System/Library/PrivateFrameworks/StoreServices.framework/Versions/A/StoreServices (0x7fff9d55ab18) and /Applications/Airmail 3.app/Contents/Frameworks/EvernoteSDK-Mac.framework/Versions/A/EvernoteSDK-Mac (0x104c9bc68). One of the two will be used. Which one is undefined.
2018-10-24 13:39:21.850 Airmail 3[95032:4301000] [BASE] ------ ------ ------ ------ ------ ------ ------
2018-10-24 13:39:21.850 Airmail 3[95032:4301000] [BASE] Airmail Type:STORE OSX:10.14.0 Version:528
2018-10-24 13:39:34.727 Airmail 3[95032:4301000] Error loading /Users/zentavr/Library/Group Containers/2E337YPCZY.airmail/Library/Application Support/it.bloop.airmail2/Airmail/General/Plugins/AMPGpg.bundle/Contents/MacOS/AMPGpg:  dlopen(/Users/zentavr/Library/Group Containers/2E337YPCZY.airmail/Library/Application Support/it.bloop.airmail2/Airmail/General/Plugins/AMPGpg.bundle/Contents/MacOS/AMPGpg, 265): Library not loaded: @rpath/Libmacgpg.framework/Versions/B/Libmacgpg
  Referenced from: /Users/zentavr/Library/Group Containers/2E337YPCZY.airmail/Library/Application Support/it.bloop.airmail2/Airmail/General/Plugins/AMPGpg.bundle/Contents/MacOS/AMPGpg
  Reason: image not found
```

The file from @rogerwalczak works though.

**Comment by zentavr** [comment]
They did a build of v.9 and it does not work at Mojave as well :(
```
2018-10-24 18:55:00.019 Airmail 3[98550:4479003] Error loading /Users/zentavr/Library/Group Containers/2E337YPCZY.airmail/Library/Application Support/it.bloop.airmail2/Airmail/General/Plugins/AMPGpg.bundle/Contents/MacOS/AMPGpg:  dlopen(/Users/zentavr/Library/Group Containers/2E337YPCZY.airmail/Library/Application Support/it.bloop.airmail2/Airmail/General/Plugins/AMPGpg.bundle/Contents/MacOS/AMPGpg, 265): Library not loaded: @rpath/Libmacgpg.framework/Versions/B/Libmacgpg
  Referenced from: /Users/zentavr/Library/Group Containers/2E337YPCZY.airmail/Library/Application Support/it.bloop.airmail2/Airmail/General/Plugins/AMPGpg.bundle/Contents/MacOS/AMPGpg
  Reason: image not found
```

**Comment by adamierymenko** [comment]
Why not build GPG support into Airmail?

It would be fine to make it a more expert option that the user must enable. Just look for 'gpg' in /usr/bin and /usr/local/bin and also provide an option to input the location of the GPG binary.

Most GPG users install via Homebrew, which puts it in /usr/local/bin.

This would really be a killer feature.

Why is there some law that says that any cryptographic extension must be impossible to use?

**Comment by rogerwalczak** [comment]
I second this wholeheartedly. And when I think about gpg support in both desktop and mobile version … hmm … killer feature indeed.

**Comment by hellais** [comment]
I was able to get the plugin working again by rebuilding it from master (following this suggestion from @rogerwalczak). I actually only had to copy `Libmacgpg.framework` (and remove references to the Libmacgpg.framework).

This is what `otool -L` looks like on a working build:
```
/Users/MYUSER/Library/Group Containers/2E337YPCZY.airmail/Library/Application Support/it.bloop.airmail2/Airmail/General/Plugins/AMPGpg.bundle/Contents/MacOS/AMPGpg:
	/System/Library/Frameworks/Cocoa.framework/Versions/A/Cocoa (compatibility version 1.0.0, current version 23.0.0)
	/Library/Frameworks/Libmacgpg.framework/Versions/B/Libmacgpg (compatibility version 2.0.0, current version 2.0.0)
	@executable_path/../Frameworks/AMPluginFramework.framework/Versions/A/AMPluginFramework (compatibility version 1.0.0, current version 1.0.0)
	/System/Library/Frameworks/Foundation.framework/Versions/C/Foundation (compatibility version 300.0.0, current version 1560.12.0)
	/usr/lib/libobjc.A.dylib (compatibility version 1.0.0, current version 228.0.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1252.200.5)
	/System/Library/Frameworks/AppKit.framework/Versions/C/AppKit (compatibility version 45.0.0, current version 1671.10.106)
	/System/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation (compatibility version 150.0.0, current version 1560.12.0)
```

**Comment by 0x-2a** [comment]
@hellais If you've got a successful build, could you upload a zip for us to grab? I followed the exact steps you did with the same otool output, but the build does not work in Airmail 3.6.50 (528)

**Comment by 0x-2a** [comment]
Never mind, I got it sorted... here's the latest that works with Airmail 3.6.50 (528)
1) Install gpg tools https://gpgtools.org/
2) Use this build: [AMPGpg.bundle.zip](https://github.com/Airmail/AirmailPlugIn-Framework/files/2630166/AMPGpg.bundle.zip)

For others in the future, here's the step by step I did to build (needs an apple developer id)
```
git clone --recursive https://github.com/GPGTools/Libmacgpg.git
cd Libmacgpg
make

cd ..
git clone https://github.com/Airmail/AirmailPlugIn-Framework.git
open AirmailPlugin-Framework/AMPGpg/AMPGpg.xcodeproj
# right click Libmacgpg.framework, remove
# drag Libmacgpg/build/Release/Libmacgpg.framework into the project, yes to copy if needed
# Build

# Your bundle output path will be somewhere like this ~/Library/Developer/Xcode/DerivedData/AMPGpg-adsxgfwhkkihclegquhtuwrnfebj/Build/Products/Debug/AMPGpg.bundle 

# Copy the above into your airmail plugin dir... something like this:
~/Library/Group Containers/2E337YPCZY.airmail/Library/Application Support/it.bloop.airmail2/Airmail/General/Plugins/AMPGpg.bundle 
```

**Comment by yannickmcosta** [comment]
Looks like that's semi working for me. I'm having an issue with the encryption option on this, not sure if anyone else is.

I can sign email, but even if a recipients public key is in my keychain, I can't select encryption. I can however select to encrypt the mail if I select an email address for which I have the *secret* key, such as another email address I control.

**Comment by 0x-2a** [comment]
@yannickmcosta same -- i can (1) decrypt emails (2) reply encrypted to anyone (3) only compose encrypted to myself.

**Comment by 0x-2a** [comment]
@Bloophub is this on the airmail side of things or the plugin? Appreciate your thoughts.

**Comment by hellais** [comment]
I believe the PGP plugin in Airmail has a lot of problems, actually.

I attempted fixing them in this PR: https://github.com/Airmail/AirmailPlugIn-Framework/pull/33, which actually was landed in master without even addressing my open questions or removing the log debug lines...

To be honest this makes me quite sad, because Airmail is such a nice emails client, but the fact that the PGP plugin is so badly maintained and supported is quite a problem.

As a developer I would be happy to help fix it and take up maintaining it (and I bet other devs in this thread would also be glad to lend a hand), yet this cannot happen unless there is some better interaction with your community.

Open source is not just about putting the code out there, it's also being available to help devs help you!

**Comment by RicoLaaa** [comment]
any news on this issue?

**Comment by sgcoffee** [comment]
Need to re-sign to GitHub to comment on this issue.

To get PGP working with mail, I changed over to Canary mail app. Which got PGP support right build in, and works fine, but haven't enjoyed Canary's UI and functionality all the time. Missed a lot of features. Anyway:
That's why I brought Airmail in terms of a much better UI and app feeling. But need urgently PGP support. I am using mail mostly for business, and would like to keep certain communication encrypted.

I am not a developer at all. But I'd pay 50USD if some one writes a serious working plug-in!

**Comment by zentavr** [comment]
@sgcoffee - the zip from [this comment above](
https://github.com/Airmail/AirmailPlugIn-Framework/issues/34#issuecomment-442918633) works for me with the latest Airmail on latest High Sierra.

**Comment by sgcoffee** [comment]
@zentavr - Thank you. The plugin gets recognized now, but only PGP signing is possible. GPG Keychain is running. Apple Mail doesn't have any issues.
macOS 10.14.2
Airmail 3.6.56 (540)

**Comment by zentavr** [comment]
@sgcoffee, strange, but I’m able to encrypt/decrypt the mails

**Comment by sgcoffee** [comment]
Ok, I could decrypt one older mail for one mail account, which I tried at first. But I couldn't answer encrypted. Nor send an encrypted new mail to this recipient.
I even tried another old encrypted mail from another account. Didn't work.
I guess, why it doesn't work: I don't get the option to enter the passphrase. It did at the first account.

**Comment by sgcoffee** [comment]
There is a another problem. Attachments and inline graphics in every mail, don't get shown at all, if the plug-in is active. Deactivating the plug-in restores images again. That's an annoying bug.

**Comment by davidcorbin** [comment]
Still having issues getting Airmail to find the plugin.

Airmail version 3.6.56 (540)
GpgTools 2018.5 2368 

<img width="882" alt="screen shot 2019-01-11 at 5 46 12 pm" src="https://user-images.githubusercontent.com/5752872/51063462-18313a80-15c9-11e9-9068-75b402389c00.png">
<img width="828" alt="screen shot 2019-01-11 at 5 46 07 pm" src="https://user-images.githubusercontent.com/5752872/51063467-1ebfb200-15c9-11e9-812a-519dc7e1861d.png">

**Comment by paulgronke** [comment]
Was hoping this might get resolved with Mojave. I can't use and can't recommend AirMail if it doesn't work with GPG (and I suppose bigger point, doesn't work with one of its own advertised plugins).

**Comment by paulgronke** [comment]
> Still having issues getting Airmail to find the plugin.
> 
> Airmail version 3.6.56 (540)
> GpgTools 2018.5 2368
> 
> <img alt="screen shot 2019-01-11 at 5 46 12 pm" width="882" src="https://user-images.githubusercontent.com/5752872/51063462-18313a80-15c9-11e9-9068-75b402389c00.png">
> 
> <img alt="screen shot 2019-01-11 at 5 46 07 pm" width="828" src="https://user-images.githubusercontent.com/5752872/51063467-1ebfb200-15c9-11e9-812a-519dc7e1861d.png">

Pre-Mojave, AirMail saw the plugin, but it couldn't unencrypt attachments. Now, it doesn't even recognize the plugin, same as the user above.

**Comment by kiela** [comment]
I still have this issue with version 3.6.58 (546). [Build attached by @y3sh](https://github.com/Airmail/AirmailPlugIn-Framework/issues/34#issuecomment-442918633) used to work for me but not after last Airmail update.
@y3sh would you be so kind and prepare updated build maybe?

**Comment by 0x-2a** [comment]
@kiela Sure... here's a new build, but it seems only decrypt is working for me. 

[AMPGpg.bundle-2019-03-23.zip](https://github.com/Airmail/AirmailPlugIn-Framework/files/2999685/AMPGpg.bundle-2019-03-23.zip)

I was thinking about spending some time trying to fix more issues here but a friend pointed me to [Airmail's privacy policy](https://www.iubenda.com/privacy-policy/558233/full-legal). I have concerns about what airmail collects/retains/distributes as well as what it has access to while my mail is decrypted. Unless something changes why bother with the security theater?

Here's an update step-by-step for others in the future (requires an apple developer id)
```
git clone --recursive https://github.com/GPGTools/Libmacgpg.git
cd Libmacgpg
make
# If you get an "xcdoebuild requires Xcode error:
# sudo xcode-select -s /Applications/Xcode.app/Contents/Developer

cd ..
git clone https://github.com/Airmail/AirmailPlugIn-Framework.git
open AirmailPlugin-Framework/AMPGpg/AMPGpg.xcodeproj
# right click Libmacgpg.framework, remove
# drag Libmacgpg/build/Release/Libmacgpg.framework into the project, yes to copy if needed
# Click on AMPGpg > Signing (Debug) > Set your apple id > Signing Certificate > Mac Developer
# Product > Build

# Your bundle output path will be somewhere like this ~/Library/Developer/Xcode/DerivedData/AMPGpg-adsxgfwhkkihclegquhtuwrnfebj/Build/Products/Debug/AMPGpg.bundle 

# Copy the above into your airmail plugin dir... something like this:
~/Library/Group Containers/2E337YPCZY.airmail/Library/Application Support/it.bloop.airmail2/Airmail/General/Plugins/AMPGpg.bundle 
```

**Comment by KodaKoder** [comment]
We don’t collect or distribute data we simply store user password if you want push notification in airmail for iOS and if you use gmail just user + token, we are not interested in user data, any other interpretation of the user policy is wrong

**Comment by 0x-2a** [comment]
@KodaKoder regardless of what airmail does right now, there are concerning parts of the policy. Consider recommending airmail for corporate adoption. These policies conflict with most corporate policies regarding sensitive data.

> We might discharge Personal Information when we trust in accordance with some basic honesty that discharge is important to agree to the law

> Bloop S.r.l uses cookies to help Airmail identify and track visitors, their usage of Bloop S.r.l website, and website access preferences.

> Legal action
> The User's Personal Data may be used for legal purposes by the Owner in Court or in the stages leading to possible legal action arising from improper use of this Application or the related Services. The User declares to be aware that the Owner may be required to reveal personal data upon request of public authorities.

> Bloop S.r.l cannot guarantee the security of Personal Information. 

> Unauthorized entry or use, hardware or software failure, and other factors, may compromise the security of user information at any time.

> The services contained in this section enable the Owner to monitor and analyze web traffic and can be used to keep track of User behavior.
> 
> HockeyApp (Bit Stadium GmbH)
> HockeyApp is an analytics service provided by Bit Stadium GmbH.
> Personal Data collected: Cookies; Usage Data.
> 
> Place of processing: Germany – Privacy Policy.


> Managing contacts and sending messages
> This type of services makes it possible to manage a database of email contacts, phone contacts or any other contact information to communicate with the User.
> These services may also collect data concerning the date and time when the message was viewed by the User, as well as when the User interacted with it, such as by clicking on links included in the message.

**Comment by KodaKoder** [comment]
Seems you are reading the web site policy and not the app policy
Thanks to let us know ;)

**Comment by 0x-2a** [comment]
Where are the macos and ios policies?

**Comment by KodaKoder** [comment]
inside the apps, there is a link to the privacy policy

**Comment by compuguy** [comment]
@y3sh I can confirm this as well. The only thing that seems to work is the signing of emails.

**Comment by ghost** [comment]
OK, now. Can anyone from the **Airmail Team** tell, WHEN the plugin will be recognised? Thanks to y3sh, with his build at least signing emails is possible. However, I need encryption. Yes, you have my money, but I cannot recommend it (although the rest works fine). I would stop using it, if I cannot get a date when this bug will be fixed!!

**Comment by KodaKoder** [comment]
The plugin issues are related to the new Hardened Runtime Entitlements Apple introduced with 10.14
there are some news about this in upcoming WWDC and we will revise the plugins.
However the plugins are open source and not part of the main project on the Mac App Store

**Comment by AntonioMeireles** [comment]
> (...)
> However the plugins are open source and not part of the main project on the Mac App Store

True, but fact is - the plugins provide key functionality that is just missing in "main project" (and which IMHO *should* _just_ be there...)

**Comment by KodaKoder** [comment]
No, encryption is external to the app, but I understand your "in my honest opinion" :)

**Comment by sbmueller** [comment]
With @y3sh s Plugin file, the plugin is recognized again. However, now all special characters (#$%) in *all* my mails (even unencrypted) are broken (@ becomes =40 for instance).

**Comment by juhoffma** [comment]
@y3sh file works for me, so far no special characters.

**Comment by phaus** [comment]
Does the Plugin Support rfc4880 (inline / ASCII Armored Messages) ?

I had a look into the code and the check seems to be against mimeType `application/pgp-signature` or `application/pgp-encrypted` to detect encrypted yes/no.

I have here a mail with mimeType `text/plain; charset="ISO-8859-15"` and `application/octet-stream;`. It was produces by Thunderbird/Enigmail.

**Comment by rogerwalczak** [comment]
@sbmueller I've come across similar issue. This was due to mishandling single part MIME messages. I've submitted a pull request for this but actual pulling may take time looking at the plugin history. In the meantime you may wish to check out the prebuilt plugin with the fix implemented:
https://github.com/rogerwalczak/AirmailPlugIn-Framework/releases/tag/v1.0-beta.8-rw.1

One warning: I'm not a real developer. Just a frustrated user

**Comment by sbmueller** [comment]
@rogerwalczak thanks for the attempt, however this plugin is not recognized again by Airmail

**Comment by rogerwalczak** [comment]
@sbmueller 
Sorry. Forgot to include libmacgpg in the bundle. Should be better now.

**Comment by sbmueller** [comment]
@rogerwalczak works, you're the best :)

**Comment by cywtf** [comment]
I installed the bundle by @rogerwalczak and the plugin is now listed and active. How do you decrypt an email? There is no UI option, nothing in the menu, nada.

**Comment by RicoLaaa** [comment]
@rootion the emails are decrypted automatically you don't have to perform any action. Make sure the certificates are installed on your computer though.
For encryption/signing you will have 2 buttons on the mail editor. Again if you don't see them that means you didn't install the certs on the computer.

**Comment by chrismaltese** [comment]
@rogerwalczak Many thanks for your effort. Works great on my system.

**Comment by sbmueller** [comment]
Ha! Too good to be true. I now see an issue that some mails are displayed empty, while in fact they have content. Took me a while to track this down, but when disabling GPG Plugin, the mails are displayed correctly.
<img width="816" alt="Bildschirmfoto 2019-08-23 um 20 52 59" src="https://user-images.githubusercontent.com/7465688/63616627-460f4080-c5e8-11e9-928f-0775eefbe4e1.png">

@rogerwalczak I'm happy to debug this via DM

**Comment by rogerwalczak** [comment]
body{font-family:Helvetica,Arial;font-size:13px}Could you please provide me with raw headers of such a message? Obviously you can anonymise it.   On 23 August 2019 at 20:55:27, Sebastian Müller (notifications@github.com) wrote: 





Ha! Too good to be true. I now see an issue that some mails are
displayed empty, while in fact they have content. Took me a while
to track this down, but when disabling GPG Plugin, the mails are
displayed correctly.


—
You are receiving this because you were mentioned.
Reply to this email directly, 
view it on GitHub, or 
mute the thread.

**Comment by apertureless** [comment]
Well, the issue is still present for me. Tried to updates plugin file, but without success.

**Comment by zentavr** [comment]
I migrated to Canary Mail.
Seems like this project is dead.

**Comment by lukasz-szyszkowski** [comment]
Any news here? :)

**Comment by sbmueller** [comment]
I also switched to another client, Airmail gets worse and worse.
Good luck to you.

**Comment by k415hu** [comment]
In the recent release, this issue still persists. PGP plugin is not being recognized.

**Comment by bhean** [comment]
Here another user waiting for this feature since years... 😞

**Comment by zentavr** [comment]
@bhean i’ve already switched to Canary Mail because of that.

**Comment by craigsansam** [comment]
I wonder if this is ever going to be resolved? If not, it might be wise to remove the GPG plugin from the Airmail homepage so it doesn't mislead people.

**Comment by sbliven** [comment]
There's a new version of the GPG Plugin (Beta 1.0 (7)). At first after downloading it wasn't showing up on the list, so I found this issue. However eventually I was able to determine it wasn't loading because of code-signing issues. Reloading plugins from within airmail gave me an error:

![Screen Shot 2022-07-13 at 11 32 38](https://user-images.githubusercontent.com/595872/178706317-835f8568-fa18-4ab4-8a08-647973df659f.png)

This can be fixed by clearing the quarantine settings in a terminal

    xattr -d com.apple.quarantine $HOME/Library/Group Containers/2E337YPCZY.airmail/Library/Application Support/it.bloop.airmail2/Airmail/General/Plugins/AMPGpg.bundle

WIth this I can load the plugin & encrypt/decrypt email.

**Comment by wolasss** [comment]
Version 10 of PGP plugin crashes Airmail Version 5.5.81 (709) on MacOS 12.6 (when composing a new e-mail) :(
